### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by neekt** [outloudvi/yourbang#1]
I just tried this extension, and it's not working. It appears to be trying to redirect the searches to the location of the extension locally. The attached screenshot shows what I get after I type `! baidu test` into the URL bar.

![Screenshot from 2019-05-23 13-16-47](https://user-images.githubusercontent.com/5132610/58223539-716e5f00-7d5d-11e9-943e-de542049a21a.png)

Tested on a fresh Firefox 67.0 profile on Linux Mint Cinnamon 19.1

It would be great if you could get this working! Cheers

**Comment by outloudvi** [comment]
tl;dr fixed in bc3f069 and it's expected to work on v1.1.0 (which is released earlier today).

Feel free to reopen if you are still experiencing problems after updating.

**Comment by outloudvi** [comment]
![image](https://user-images.githubusercontent.com/19144373/58233226-0711ea80-7d6e-11e9-8f42-c6f0aa2f1a75.png)

The actual case is that, before v1.1.0 (which is the version you're using), people need to manually select the second selection to go to the correct page, so it is expected if you are selecting the first selection and go to this page.

And that should be fixed in v1.1.0. In v1.1.0, you can just go into the first selection and things ought to work.

**Comment by neekt** [comment]
Thanks for getting onto this so quickly! Your baked-in bangs work just fine now (bili, baidu, zhwp), but any searches I add myself are being redirected to duckduckgo, which is strange because duckduckgo isn't even my default search engine.

It looks like it will work when I click the second selection:
![Screenshot from 2019-05-25 00-21-15](https://user-images.githubusercontent.com/5132610/58334584-336b5b00-7e83-11e9-8742-79eb4c9f7bd1.png)

But then I'm taken to:
![Screenshot from 2019-05-25 00-21-56](https://user-images.githubusercontent.com/5132610/58334590-35cdb500-7e83-11e9-94e8-37a8824d8641.png)

Here's my JSON string:
`{"bili":"https://bilibili.com/video/%s","baidu":"https://baidu.com/s?wd=%s","zhwp":"https://zh.wikipedia.org/wiki/%s","bomgov":"http://search.bom.gov.au/s/search.html?query=%s&collection=bom&Submit=Search"}`

**Comment by outloudvi** [comment]
Tracking on it.

**Comment by outloudvi** [comment]
This should be fixed at 86177e1e, which is published as a part of v1.1.1.
Feel free to reopen if it's not working.
